<a href="https://colab.research.google.com/github/kpullabhotla/NeuralNetworks/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: KAMESWARA PULLABHOTLA
# Z-ID: Z1891893

# Assignment - 1

In [ ]:
#####################################
# Imports, Cloning Files From GIT Repo
######################################
from sklearn.metrics import confusion_matrix
import numpy as np

# Clone git repo
! git clone https://github.com/kpullabhotla/dataSets.git

fatal: destination path 'dataSets' already exists and is not an empty directory.


In [ ]:
####################################
# Segregating Input Into 28X28 Pixels
####################################

def seg_list(inp_list):
  data = []
  final_list = []
  n=784
  i = 0
  
  for ele in inp_list:

    new_line = ele.replace(" ","0")
    new_line = new_line.replace("+","1")
    new_line = new_line.replace("#","1")

    data.append(list(new_line[:28]))


  flat_map = np.array(list(np.concatenate(data).flat))
  flat_list = np.array(list(map(int, flat_map)))
  my_new_list = np.array([flat_list[i:i + n] for i in range(0, len(flat_list), n)])
  return my_new_list

In [ ]:
#################################
# Importing Training & Test Data
#################################

# Reading training feature data
train_file = open("/content/dataSets/digitdata/trainingimages.txt",'r')
inp_train_list = (train_file.read()).splitlines()
final_train_list = seg_list(inp_train_list)
#print(final_train_list.shape,type(final_train_list),len(final_train_list))

# Reading training label data
train_label_list = np.genfromtxt("/content/dataSets/digitdata/traininglabels.txt",dtype=np.integer)
print(train_label_list.shape,type(train_label_list),len(train_label_list))

# Reading test feature data
test_file = open("/content/dataSets/digitdata/testimages.txt",'r')
inp_test_list = (test_file.read()).splitlines()
final_test_list = seg_list(inp_test_list)
#print(final_test_list.shape,type(final_test_list),len(final_test_list))

# Reading test label data
test_label_list = np.genfromtxt("/content/dataSets/digitdata/testlabels.txt",dtype=np.integer)
#print(test_label_list.shape,type(test_label_list))

(5000,) <class 'numpy.ndarray'> 5000


In [ ]:
#################################
# Calculating prior probability
#################################

features_per_class={}
priors_new ={}

for idx,label in enumerate(train_label_list):
  count = np.count_nonzero(train_label_list == label)
  features_per_class[int(label)] = count
  priors_new[int(label)] = np.log(count/len(train_label_list))

In [ ]:
#################################
# Applying Smoothing
#################################

import pandas as pd
k=1

image_df = pd.DataFrame(final_train_list)
labels = list(train_label_list)
image_df['label'] = labels
prob_pixel_count_zero = image_df.count

prior_count =  pd.Series(features_per_class)+(2*k)
sum_pixel_one_df = k+image_df.groupby(image_df['label']).sum()
sum_pixel_one_df = sum_pixel_one_df.div(prior_count,axis=0)


In [ ]:
#################################
# Predicting Test Samples
#################################

predicted_labels =[]

for image_test in final_test_list:
  posterior_prob = []
  for clas in range(10):
    likelihood = 1
    for pixel in range(len(image_test)):
      if image_test[pixel]==1:
        feature_prob = sum_pixel_one_df.iloc[clas,pixel]
      else:
        feature_prob = 1 - sum_pixel_one_df.iloc[clas,pixel]
      likelihood = likelihood*feature_prob
    posterior_prob.append(likelihood)
  predicted_labels.append(posterior_prob.index(max(posterior_prob)))

In [ ]:
#################################
# Building Confusion Matrix (in %'s)
#################################

conf_matrix = confusion_matrix(test_label_list,predicted_labels)/10

print("Confusion Matrix For The Given Dataset in (%):\n\n",conf_matrix)

Confusion Matrix For The Given Dataset in (%):

 [[ 7.6  0.   0.1  0.   0.1  0.5  0.4  0.   0.3  0. ]
 [ 0.  10.4  0.1  0.   0.   0.2  0.1  0.   0.   0. ]
 [ 0.2  0.4  7.6  0.6  0.1  0.   0.6  0.1  0.5  0.2]
 [ 0.   0.2  0.   8.   0.   0.2  0.2  0.6  0.2  0.6]
 [ 0.   0.1  0.   0.   8.1  0.   0.3  0.1  0.2  1.9]
 [ 0.2  0.2  0.1  1.5  0.3  5.9  0.1  0.1  0.2  0.6]
 [ 0.1  0.6  0.5  0.   0.7  0.5  6.5  0.   0.2  0. ]
 [ 0.   0.7  0.3  0.   0.3  0.   0.   7.6  0.2  1.5]
 [ 0.2  0.3  0.3  1.3  0.2  0.5  0.1  0.1  6.2  1.1]
 [ 0.1  0.2  0.1  0.3  0.9  0.2  0.   0.2  0.1  7.9]]


In [ ]:
#################################
# Calculating Accuracy
#################################

predict_values = np.array(predicted_labels)
accuracy = predict_values == test_label_list
print("Percentage of accuracy for the given dataset is: ",accuracy.sum()/10,"%")

Percentage of accuracy for the given dataset is:  75.8 %


In [ ]:
########################################
# Printing K value
#########################################

print("K value is>> ",k)


K value is>>  7


In [ ]:
##########################################
# Displaying Predicted With Correct Labels
##########################################

final_classification = pd.DataFrame(predict_values,test_label_list)
SerialNo = np.arange(len(final_classification))

final_classification = pd.DataFrame({"SerialNo":range(1,1001),"p":predict_values,"q":test_label_list})
print(final_classification)


K value is>>  7
     SerialNo  p  q
0           1  7  9
1           2  0  0
2           3  2  2
3           4  3  5
4           5  1  1
..        ... .. ..
995       996  0  0
996       997  6  6
997       998  3  3
998       999  9  9
999      1000  5  5

[1000 rows x 3 columns]
